# Generated by Django 4.0.4 on 2022-05-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Member_Email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Member_Password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Member_Username',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Member_fName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Member_lName',
        ),
    ]
