# Generated by Django 4.0.4 on 2022-05-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_remove_member_member_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Member_Id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.member'),
        ),
    ]
