# Generated by Django 4.0.4 on 2022-05-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_remove_transaction_member_id_transaction_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='Promotion_Pic',
            field=models.ImageField(default='promotion/default-promotion.png', upload_to='promotion'),
        ),
    ]
