# Generated by Django 4.0.4 on 2022-05-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0004_alter_promotion_promotion_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='Promotion_Pic',
            field=models.ImageField(default='promotion/default-promotion.jpg', upload_to='promotion'),
        ),
    ]
