# Generated by Django 4.0.4 on 2022-05-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_alter_promotion_promotion_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Staff_id',
        ),
        migrations.AddField(
            model_name='member',
            name='Member_isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
