# Generated by Django 4.0.4 on 2022-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0006_remove_member_staff_id_member_member_isstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Staff_Position',
            field=models.CharField(choices=[('AD', 'ADMIN'), ('MA', 'MANAGER'), ('ST', 'STAFF')], default='ST', max_length=10),
        ),
    ]
