# Generated by Django 4.0.4 on 2022-05-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_alter_staff_staff_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Member_isStaff',
        ),
    ]
