# Generated by Django 4.0.4 on 2022-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_remove_member_member_isstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Staff_Position',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('STAFF', 'STAFF')], default='STAFF', max_length=10),
        ),
    ]
