# Generated by Django 4.0.4 on 2022-05-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_alter_staff_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Hotel_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.hotel'),
        ),
    ]
