# Generated by Django 4.0.4 on 2022-05-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0010_alter_staff_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Hotel_Id',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='allbook',
            name='Room_Id',
        ),
        migrations.RemoveField(
            model_name='allbook',
            name='Transaction_Id',
        ),
        migrations.RemoveField(
            model_name='getnews',
            name='Member_Id',
        ),
        migrations.RemoveField(
            model_name='getnews',
            name='News_Id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Payment_Id',
        ),
        migrations.AddField(
            model_name='allbook',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.room'),
        ),
        migrations.AddField(
            model_name='allbook',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.transaction'),
        ),
        migrations.AddField(
            model_name='getnews',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.member'),
        ),
        migrations.AddField(
            model_name='getnews',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.news'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.payment'),
        ),
    ]
