# Generated by Django 4.0.4 on 2022-05-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0013_remove_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Promotion_Id',
        ),
        migrations.AddField(
            model_name='payment',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.promotion'),
        ),
    ]
