# Generated by Django 4.0.4 on 2022-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0015_remove_transaction_transaction_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_Allprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Vat10',
            field=models.FloatField(),
        ),
    ]
