# Generated by Django 4.0.4 on 2022-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0003_alter_member_member_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_Pic',
            field=models.ImageField(upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Member_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='News_Pic',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Slip',
            field=models.ImageField(upload_to='slip'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='Promotion_Pic',
            field=models.ImageField(upload_to='promotion'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='Type_Pic',
            field=models.ImageField(upload_to='roomdemo'),
        ),
    ]
