# Generated by Django 4.0.4 on 2022-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0004_alter_hotel_hotel_pic_alter_member_member_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Member_Pic',
            field=models.ImageField(blank=True, default='profile/default-user.jpg', null=True, upload_to='profile'),
        ),
    ]
